// Dummy data for the timesheet table
import type { TimesheetRow, DayEntry, DayKey } from "./types"

function computeTotals(days: Record<DayKey, DayEntry>) {
  let regular = 0
  let overtime = 0
  for (const k of Object.keys(days) as DayKey[]) {
    const d = days[k]
    if (d.status === "W") {
      const h = Math.max(0, d.hours ?? 0)
      regular += Math.min(8, h)
      overtime += Math.max(0, h - 8)
    }
  }
  return {
    regularHours: regular,
    overtimeHours: overtime,
    totalHours: regular + overtime,
  }
}

export function getTimesheetRows(): TimesheetRow[] {
  const rawTimesheetData = [
    {
      id: "1",
      name: "John",
      title: "Fuel Operations Manager",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 11 },
        Tue: { status: "L" as const },
        Wed: { status: "W" as const, hours: 11 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 6 },
      },
    },
    {
      id: "2",
      name: "Sarah Williams",
      title: "Senior Drilling Engineer",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 8 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 6 },
        Thu: { status: "L" as const },
        Fri: { status: "W" as const, hours: 9 },
        Sat: { status: "W" as const, hours: 7 },
      },
    },
    {
      id: "3",
      name: "Olivia Chen",
      title: "Pipeline Inspection Specialist",
      days: {
        Sun: { status: "PH" as const },
        Mon: { status: "L" as const },
        Tue: { status: "W" as const, hours: 13 },
        Wed: { status: "W" as const, hours: 8 },
        Thu: { status: "W" as const, hours: 14 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 10 },
      },
    },
    {
      id: "4",
      name: "Rajesh Sharma",
      title: "Process Safety Officer",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 8 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 8 },
        Thu: { status: "W" as const, hours: 12 },
        Fri: { status: "W" as const, hours: 8 },
        Sat: { status: "W" as const, hours: 8 },
      },
    },
    {
      id: "5",
      name: "Fatima Noor",
      title: "LNG Operations Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 8 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 11 },
        Thu: { status: "W" as const, hours: 8 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 10 },
      },
    },
    {
      id: "6",
      name: "Elena Petrova",
      title: "Subsea Installation Engineer",
      days: {
        Sun: { status: "PH" as const },
        Mon: { status: "W" as const, hours: 8 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 10 },
      },
    },
    {
      id: "7",
      name: "Yusuf Ibrahim",
      title: "Environmental Compliance Officer",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 8 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 8 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 10 },
      },
    },
    {
      id: "8",
      name: "Harini Nair",
      title: "Pump Station Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 8 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "WO" as const },
        Sat: { status: "W" as const, hours: 10 },
      },
    },
    {
      id: "9",
      name: "David Miller",
      title: "Tank Farm Operations Manager",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 9 },
        Tue: { status: "W" as const, hours: 13 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 8 },
        Fri: { status: "W" as const, hours: 12 },
        Sat: { status: "W" as const, hours: 10 },
      },
    },
    {
      id: "10",
      name: "Aisha Al-Mutairi",
      title: "Tank Farm Operations Manager",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 8 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 8 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 10 },
      },
    },
    {
      id: "11",
      name: "Priya Ramesh",
      title: "Subsea Pipeline Engineer",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 7 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 12 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 10 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    {
      id: "12",
      name: "Mohammed",
      title: "Storage Facility Civil Supervisor",
      days: {
        Sun: { status: "WO" as const },
        Mon: { status: "W" as const, hours: 6 },
        Tue: { status: "W" as const, hours: 10 },
        Wed: { status: "W" as const, hours: 10 },
        Thu: { status: "W" as const, hours: 10 },
        Fri: { status: "W" as const, hours: 10 },
        Sat: { status: "W" as const, hours: 50 },
      },
    },
    
  ]

  return rawTimesheetData.map((entry) => {
    const totals = computeTotals(entry.days)
    return {
      ...entry,
      ...totals,
    }
  })
}
